services:
  postgres:
    image: postgres:16
    container_name: finance_etl_postgres
    environment:
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_password
      POSTGRES_DB: finance_etl
    ports:
      - "5432:5432"
    volumes:
      - finance_etl_data:/var/lib/postgresql/data

volumes:
  finance_etl_data: