"""create initial schema

Revision ID: 27f3ec6ceb76
Revises: 
Create Date: 2026-07-05 21:52:36.917937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f3ec6ceb76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=True)
    op.create_table('etl_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('daily_return', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('ma7', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('ma30', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('ema20', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('rsi14', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('atr14', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('volatility', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'timestamp', name='uq_daily_metrics_asset_timestamp')
    )
    op.create_index(op.f('ix_daily_metrics_asset_id'), 'daily_metrics', ['asset_id'], unique=False)
    op.create_index(op.f('ix_daily_metrics_timestamp'), 'daily_metrics', ['timestamp'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'timestamp', name='uq_price_history_asset_timestamp')
    )
    op.create_index(op.f('ix_price_history_asset_id'), 'price_history', ['asset_id'], unique=False)
    op.create_index(op.f('ix_price_history_timestamp'), 'price_history', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_timestamp'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_asset_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_daily_metrics_timestamp'), table_name='daily_metrics')
    op.drop_index(op.f('ix_daily_metrics_asset_id'), table_name='daily_metrics')
    op.drop_table('daily_metrics')
    op.drop_table('etl_runs')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
